'use client'

import { useEffect, useRef, useState } from 'react'
import { Button } from '@/components/ui/button'
import { Loader2, Terminal, AlertCircle, CheckCircle2, XCircle, FileQuestion } from 'lucide-react'
import { checkFiles, type FileCheck } from '@/lib/hooks/use-preflight'

// Serve js-dos locally (public/js-dos.js) to avoid CDN version surprises.
// Generated by: cp node_modules/js-dos/dist/js-dos.js public/js-dos.js
const JSDOS_LOCAL = '/js-dos.js'
const LOAD_TIMEOUT_MS = 25_000

type Status = 'idle' | 'checking' | 'preflight-error' | 'loading' | 'running' | 'error'

interface DosEmulatorProps {
  romUrl: string
  title: string
}

declare global {
  interface Window {
    Dos?: (el: HTMLElement, opts: Record<string, unknown>) => Promise<{ stop(): void }>
  }
}

function loadScript(src: string): Promise<void> {
  return new Promise((resolve, reject) => {
    if (document.querySelector(`script[src="${src}"]`)) { resolve(); return }
    const s = document.createElement('script')
    s.src = src
    s.onload  = () => resolve()
    s.onerror = () => reject(new Error(`No se pudo cargar: ${src}`))
    document.head.appendChild(s)
  })
}

export function DosEmulator({ romUrl, title }: DosEmulatorProps) {
  const containerRef = useRef<HTMLDivElement>(null)
  const instanceRef  = useRef<{ stop(): void } | null>(null)
  const timerRef     = useRef<ReturnType<typeof setTimeout> | null>(null)

  const [status,  setStatus]  = useState<Status>('idle')
  const [error,   setError]   = useState<string | null>(null)
  const [checks,  setChecks]  = useState<FileCheck[]>([])
  const [logs,    setLogs]    = useState<string[]>([])

  function addLog(msg: string) {
    setLogs(prev => [`[${new Date().toLocaleTimeString()}] ${msg}`, ...prev].slice(0, 60))
    console.log('[DOS]', msg)
  }

  async function launch() {
    if (!containerRef.current) return
    setStatus('checking')
    setError(null)
    setLogs([])
    addLog(`Verificando archivos para "${title}"…`)

    // ── Preflight ──────────────────────────────────────────────────────────
    const results = await checkFiles([
      { url: romUrl, label: 'Bundle .jsdos', required: true,
        hint: `Coloca el archivo en /public${romUrl}` },
    ])
    setChecks(results)

    const missing = results.filter(r => r.required && r.status !== 'ok')
    results.forEach(r =>
      addLog(r.status === 'ok'
        ? `✅ ${r.label} — ${r.size ?? 'OK'}`
        : `❌ ${r.label} — no encontrado`)
    )

    if (missing.length > 0) {
      setStatus('preflight-error'); return
    }

    // ── Load SDK ──────────────────────────────────────────────────────────
    setStatus('loading')
    addLog('Cargando js-dos (local)…')

    timerRef.current = setTimeout(() => {
      addLog('⏱ Timeout — js-dos o la ROM tardaron demasiado')
      setError('Tiempo de espera agotado. Revisa la consola del navegador.')
      setStatus('error')
    }, LOAD_TIMEOUT_MS)

    try {
      await loadScript(JSDOS_LOCAL)
      if (!window.Dos) throw new Error('window.Dos no está disponible tras cargar el SDK.')
      addLog('✅ SDK cargado. Iniciando DOSBox…')

      // Watch for DOSBox canvas to appear (js-dos v8 injects it asynchronously)
      const observer = new MutationObserver(() => {
        if (!containerRef.current) return
        const canvas = containerRef.current.querySelector('canvas')
        if (canvas) {
          observer.disconnect()
          if (timerRef.current) clearTimeout(timerRef.current)
          addLog('✅ Canvas DOSBox detectado — emulador activo')
          setStatus('running')
        }
      })
      observer.observe(containerRef.current, { childList: true, subtree: true })

      instanceRef.current = await window.Dos(containerRef.current, { url: romUrl })
      addLog('✅ Dos() resuelto — DOSBox iniciado')
    } catch (e) {
      if (timerRef.current) clearTimeout(timerRef.current)
      const msg = e instanceof Error ? e.message : 'Error desconocido'
      addLog(`❌ ${msg}`)
      setError(msg)
      setStatus('error')
    }
  }

  useEffect(() => {
    return () => {
      if (timerRef.current) clearTimeout(timerRef.current)
      instanceRef.current?.stop()
    }
  }, [])

  return (
    <div className="flex flex-col gap-3">
      <div
        className="relative w-full rounded-xl bg-black"
        style={{ aspectRatio: '4/3', minHeight: 360 }}
      >
        <div
          ref={containerRef}
          className="jsdos-container absolute inset-0 w-full h-full overflow-hidden rounded-xl"
        />

        {status !== 'running' && (
          <div className="absolute inset-0 z-10 flex flex-col items-center justify-center gap-5 bg-black/92 rounded-xl p-6">

            {status === 'idle' && (
              <>
                <Terminal className="h-14 w-14 text-violet-500 opacity-40" />
                <div className="text-center space-y-1">
                  <p className="text-white font-semibold text-lg">{title}</p>
                  <p className="text-slate-500 text-sm">MS-DOS · DOSBox WASM (js-dos v8)</p>
                </div>
                <div className="w-full max-w-sm rounded-lg border border-slate-700 bg-slate-900 px-4 py-3 text-xs space-y-2">
                  <p className="font-semibold text-slate-300">Bundle requerido</p>
                  <code className="text-violet-400 block">/public{romUrl}</code>
                  <p className="text-slate-500 border-t border-slate-700 pt-2">
                    Si DOSBox muestra &quot;Illegal command: doom&quot;, los archivos están en subcarpeta.
                    El <code className="text-slate-400">dosbox.conf</code> dentro del .jsdos debe ser:
                  </p>
                  <pre className="text-slate-400 bg-slate-800 rounded p-2 leading-5 select-all">{`[autoexec]\nmount c .\nc:\ncd doom\nDOOM.EXE`}</pre>
                </div>
                <Button onClick={launch} sz="lg" className="px-8">▶ Iniciar DOSBox</Button>
              </>
            )}

            {status === 'checking' && (
              <><Loader2 className="h-8 w-8 animate-spin text-violet-400" />
              <p className="text-slate-300 text-sm">Verificando archivos…</p></>
            )}

            {status === 'preflight-error' && (
              <div className="flex flex-col gap-4 w-full max-w-sm">
                <div className="flex items-center gap-2">
                  <AlertCircle className="h-5 w-5 text-red-400 shrink-0" />
                  <p className="text-red-300 font-semibold text-sm">Archivo no encontrado</p>
                </div>
                <PreflightList checks={checks} />
                <Button variant="outline" sz="sm" onClick={() => setStatus('idle')}>Volver</Button>
              </div>
            )}

            {status === 'loading' && (
              <><Loader2 className="h-8 w-8 animate-spin text-violet-400" />
              <p className="text-slate-300 text-sm">Iniciando DOSBox…</p></>
            )}

            {status === 'error' && (
              <div className="flex flex-col items-center gap-4 w-full max-w-sm">
                <AlertCircle className="h-8 w-8 text-red-400" />
                <p className="text-red-300 text-sm text-center">{error}</p>
                <div className="flex gap-2">
                  <Button variant="outline" sz="sm" onClick={() => setStatus('idle')}>Volver</Button>
                  <Button sz="sm" onClick={launch}>Reintentar</Button>
                </div>
              </div>
            )}
          </div>
        )}

        {/* Manual dismiss — in case MutationObserver fires late */}
        {status === 'loading' && (
          <button
            className="absolute bottom-3 right-3 z-20 text-xs text-slate-600 hover:text-slate-400 transition-colors"
            onClick={() => { if (timerRef.current) clearTimeout(timerRef.current); setStatus('running') }}
          >
            Ya cargó, quitar overlay
          </button>
        )}
      </div>

      {logs.length > 0 && (
        <div className="rounded-lg border border-slate-700 bg-slate-950 p-3">
          <p className="text-xs font-semibold text-slate-500 mb-2 uppercase tracking-wider">Debug log</p>
          <div className="flex flex-col gap-0.5 max-h-32 overflow-y-auto font-mono">
            {logs.map((l, i) => (
              <p key={i} className={`text-xs leading-5 ${l.includes('❌') ? 'text-red-400' : l.includes('✅') ? 'text-emerald-400' : l.includes('⏱') ? 'text-amber-400' : 'text-slate-400'}`}>{l}</p>
            ))}
          </div>
        </div>
      )}

      {status === 'running' && (
        <p className="text-emerald-400 text-xs">
          Emulador activo · Clic en pantalla para capturar teclado ·{' '}
          <kbd className="bg-slate-700 px-1 rounded text-slate-300">F11</kbd> pantalla completa
        </p>
      )}
    </div>
  )
}

function PreflightList({ checks }: { checks: FileCheck[] }) {
  return (
    <div className="flex flex-col gap-1.5 w-full">
      {checks.map(c => (
        <div key={c.url} className="flex items-start gap-2 rounded-lg border border-slate-700 bg-slate-900 px-3 py-2.5">
          {c.status === 'ok' ? <CheckCircle2 className="h-4 w-4 text-emerald-400 shrink-0 mt-0.5" />
            : c.status === 'missing' ? <XCircle className="h-4 w-4 text-red-400 shrink-0 mt-0.5" />
            : <FileQuestion className="h-4 w-4 text-amber-400 shrink-0 mt-0.5" />}
          <div className="min-w-0 flex-1">
            <p className="text-xs font-medium text-slate-300">{c.label}</p>
            <code className="text-xs text-slate-500 block truncate">{c.url}</code>
            {c.status === 'ok' && <p className="text-xs text-emerald-500 mt-0.5">{c.size}</p>}
            {c.status !== 'ok' && c.hint && <p className="text-xs text-amber-400 mt-0.5">{c.hint}</p>}
          </div>
        </div>
      ))}
    </div>
  )
}
